const surveyJson = {
  title: "Career Analysis Form",
  description:
    "Your privacy is important to us. All information received through our forms and other communications is subject to our Privacy Policy.",
  logoWidth: "auto",
  logoHeight: "96",
  logoPosition: "right",
  // completedHtml:
  //   '<div style="max-width:540px;text-align:left;margin:0px auto 16px auto;border: 1px solid rgba(0,0,0,0.25);padding:40px 48px 48px 48px;background-color:#fff;">\n\n<h4>Thank you for completing your patient registration form.</h4>\n<br>\n<p>Dear {firstname-for-complete-page},\n<br>\nYour information has been successfully received, and we look forward to providing you with the highest level of care. \n<br><br>\nIf you have any questions or need to schedule an appointment, please don\'t hesitate to reach out to our office. Our team is here to assist you every step of the way.\n<br><br>\nWarm regards,\n<br>\nCentral Hospital.</p>\n\n</div>',
  pages: [
    {
      name: "startpage",
      elements: [
        {
          type: "panel",
          name: "Industry",
          elements: [
            {
              type: "dropdown",
              name: "sector",
              width: "50%",
              minWidth: "256px",
              title: "Choose your career industry",
              isRequired: true,
              choices: ["IT"],
            },
          ],
          title: "Sector",
          width: "69%",
          minWidth: "256px",
        },
      ],
    },
    {
      name: "page1",
      elements: [
        {
          type: "panel",
          name: "Hard Skill",
          elements: [
            {
              type: "rating",
              name: "operating",
              title: "Rate your skill in Operating Systems",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "algorithm",
              title: "Rate your skill in Algorithms",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "programming",
              title: "Rate your skill in Programming Concepts",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "software",
              title: "Rate your skill in Software Engineering",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "network",
              title: "Rate your skill in Computer Networks",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
          ],
          title: "Hard Skill",
          isRequired: true,
          width: "69%",
          minWidth: "256px",
        },
      ],
      visibleIf: "{Sector} = 'IT'",
    },
    {
      name: "page2",
      elements: [
        {
          type: "panel",
          name: "panel5",
          elements: [
            {
              type: "rating",
              name: "architecture",
              title: "Rate your skill in Computer Architecture",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "mathematics",
              title: "Rate your skill in Mathematics",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "coding",
              title: "Rate your skill in Coding",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "logical",
              title: "Rate your skill in Logical Thinking",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
          ],
          title: "Hard Skill",
          isRequired: true,
          width: "69%",
          minWidth: "256px",
        },
      ],
      visibleIf: "{Sector} = 'IT'",
    },
    {
      name: "page3",
      elements: [
        {
          type: "panel",
          name: "panel1",
          elements: [
            {
              type: "rating",
              name: "communication",
              title: "Rate your Communication Skill",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "rating",
              name: "publicspeak",
              title: "Rate your Public Speaking Skill",
              isRequired: true,
              rateCount: 9,
              rateMin: 1,
              rateMax: 9,
              minRateDescription: "Low skill",
              maxRateDescription: "Very skillful",
              displayMode: "buttons",
            },
            {
              type: "boolean",
              name: "selflearning",
              title: "Do you have self-learning skill?",
              isRequired: true,
            },
            {
              type: "boolean",
              name: "teamwork",
              title: "Do you have Team-work skill?",
              isRequired: true,
            },
          ],
          title: "Soft Skill",
          isRequired: true,
          width: "69%",
          minWidth: "256px",
        },
      ],
      visibleIf: "{Sector} = 'IT'",
    },
    {
      name: "page4",
      elements: [
        {
          type: "panel",
          name: "panel2",
          elements: [
            {
              type: "radiogroup",
              name: "gentle",
              title: "Are you gentle or stubborn?",
              isRequired: true,
              choices: [
                {
                  value: "gentle",
                  text: "Gentle",
                },
                {
                  value: "stubborn",
                  text: "Stubborn",
                },
              ],
            },
            {
              type: "radiogroup",
              name: "management",
              title: "Which one you prefer?",
              isRequired: true,
              choices: [
                {
                  value: "Management",
                  text: "Management",
                },
                {
                  value: "Technical",
                  text: "Technical",
                },
              ],
            },
            {
              type: "radiogroup",
              name: "hardworker",
              title: "Which one you prefer?",
              isRequired: true,
              choices: [
                {
                  value: "hard worker",
                  text: "Hard Worker",
                },
                {
                  value: "smart worker",
                  text: "Smart Worker",
                },
              ],
            },
            {
              type: "boolean",
              name: "introvert",
              title: "Are you introvert?",
            },
          ],
          title: "Personality",
          isRequired: true,
          width: "69%",
          minWidth: "256px",
        },
      ],
      visibleIf: "{Sector} = 'IT'",
    },
    {
      name: "page5",
      elements: [
        {
          type: "panel",
          name: "panel3",
          elements: [
            {
              type: "dropdown",
              name: "subject",
              title: "Interested Subjects",
              isRequired: true,
              choices: [
                "Programming",
                "Networking",
                "IOT",
                "Data Engineering",
                "Computer Architecture",
                "Hacking",
                "Cloud Computing",
                "Software Engineering",
                "Management",
                "Parallel Computing",
              ],
              showOtherItem: true,
            },
            {
              type: "dropdown",
              name: "careerarea",
              title: "Interested Career Area",
              isRequired: true,
              choices: [
                "Testing",
                "System Developer",
                "Cloud Computing",
                "Security",
                "Business Analysis",
              ],
              showOtherItem: true,
            },
          ],
          title: "Interest",
          isRequired: true,
          width: "69%",
          minWidth: "256px",
        },
      ],
      visibleIf: "{Sector} = 'IT'",
    },
    {
      name: "page6",
      elements: [
        {
          type: "panel",
          name: "panel4",
          elements: [
            {
              type: "rating",
              name: "workhour",
              title: "How many hours do you want to work daily? ",
              rateCount: 5,
              rateMin: 5,
              rateMax: 9,
            },
            {
              type: "radiogroup",
              name: "salary",
              title: "Which one do you prefer?",
              choices: [
                {
                  value: "salary",
                  text: "Salary",
                },
                {
                  value: "work",
                  text: "Work Experience",
                },
              ],
            },
            {
              type: "dropdown",
              name: "company",
              title: "Type of company you want to settle in?",
              choices: [
                "Testing and Maintainance",
                "Web Services",
                "Cloud Services",
                "Product Development",
                "Finance",
              ],
              showOtherItem: true,
            },
          ],
          title: "Other",
          isRequired: true,
          width: "69%",
          minWidth: "256px",
        },
      ],
      visibleIf: "{Sector} = 'IT'",
    },
  ],
  // showCompletedPage: false,
  // navigateToUrl: "/result",

  showPageNumbers: true,
  showQuestionNumbers: "off",
  // goNextPageAutomatic: true,
  questionErrorLocation: "bottom",
  completeText: "Submit",
  questionsOnPageMode: "multiPage",
  widthMode: "static",
  width: "1024",
  headerView: "advanced",
};
export default surveyJson;
